### ISSUE TITLE
Guidance Doc Status and Ownership if Applicable

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#100]
- [x] Preface #51 (@bharveyTX )
- [x] Glossary (@tstodart ). _To be finalized_  #66 
- [x] Cloud Topology from ESR
- [x] Shared Security Model (@bharveyTX ). _In progress_ #98 
- [x] New section: Trusted Platform (@bharveyTX ) #101
- [x] TOE Identification (@bharveyTX ), _In Progress_ #82 
- [x] Cloud Equivalence Considerations. (@jgb1128 ) see Issue #103 Once integrated, mark as done @bharveyTX 
- [x] Contributors Roles in Product Evaluations. _Needs work_
- [x] Steps to optimize a PP for TOEs in a cloud environment. (@jfisherbah )  _Awaiting MDM subgroup content_ #47 also see #108
- [x] Cloud Sub-Processes . (@jdonndelinger) _Needs work_  #74 
- [x] Vulnerability Assessment Methodology _Needs work_ 
- [x] Guidance for test Environments_drafted--needs review @jdonndelinger @bharveyTX

**Comment by jgb1128** [comment]
#97 has relevant commentary

**Comment by jgb1128** [comment]
Closing!
